# BambooChat Dynamic Traefik v3 Configuration Template

http:
  routers:
    bamboochat:
      rule: "Host(`chat.seanchoi.space`)"
      entryPoints:
        - websecure
      service: bamboochat
      tls:
        certResolver: vercel

  services:
    bamboochat:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://127.0.0.1:8000"
